"""
What this suite verifies: the runtime translation helper backend.i18n resolves localized strings and plural
forms from Babel message catalogs generated by scripts/gen_locale_catalogs for the supported locales (en_US,
pt_BR), falls back to canonical English msgids when no catalog or entry is available, negotiates locale selection
from environment variables correctly, and that the checked-in default catalog tree under backend/locales exists.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import backend.i18n as i8n
import scripts.gen_locale_catalogs as gen_locales

#: Test-only catalog root under ./var/temp (project convention avoids /tmp) so generated test artifacts stay outside the checked-in tree.
TEST_LOCALES_ROOT = Path("./var/temp") / "i18n_catalogs_test"
DEFAULT_REPOS_CATALOGS_DIR: Path = Path("backend/locales")


def _build_and_repoint(monkeypatch: pytest.MonkeyPatch) -> None:
    """Generate fresh locale catalogs into ./tmp and point backend.i18n at that root before invoking lookup helpers."""
    gen_locales.build_locales(TEST_LOCALES_ROOT)
    monkeypatch.setattr(i8n, "LOCALE_CATALOGS_DIR", TEST_LOCALES_ROOT)
    i8n._catalog_for.cache_clear()


def test_en_us_identity_lookup(monkeypatch) -> None:
    """en_US is the runtime default: t() should return canonical English msgids because en strings mirror their ids."""
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "en_US")
    i8n._catalog_for.cache_clear()
    assert i8n.t("Processing your document…") == "Processing your document…"


def test_pt_br_translation_lookup(monkeypatch) -> None:
    """pt_BR should select the translated message from its locale strings file instead of falling back to English text."""
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "pt_BR")
    i8n._catalog_for.cache_clear()
    assert i8n.t("Processing your document…") == "Processando seu documento…"


def test_default_locale_used_when_env_missing(monkeypatch) -> None:
    """When neither LOCALE nor LANGUAGE is present, t() should behave as en_US identity lookup for msgids."""
    _build_and_repoint(monkeypatch)
    monkeypatch.delenv("LOCALE", raising=False)
    monkeypatch.delenv("LANGUAGE", raising=False)
    i8n._catalog_for.cache_clear()
    assert i8n.t("Processing your document…") == "Processing your document…"


def test_untranslated_msgid_falls_back_to_english(monkeypatch) -> None:
    """Unknown/untranslatable msgids should pass through unchanged in pt_BR as per fallback-by-identity t() contract."""
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "pt_BR")
    i8n._catalog_for.cache_clear()
    assert (
        i8n.t("This message id was never translated into the pt_BR catalog")
        == "This message id was never translated into the pt_BR catalog"
    )


def test_ngettext_selection_by_count(monkeypatch) -> None:
    """n() should pick the grammatical-correct plural form for a given count under each locale's Babel N-plurals rule."""
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "en_US")
    i8n._catalog_for.cache_clear()
    assert i8n.n("document", "documents", 1) == "document"
    assert i8n.n("document", "documents", 2) == "documents"
    monkeypatch.setenv("LOCALE", "pt_BR")
    i8n._catalog_for.cache_clear()
    assert i8n.n("document", "documents", 1) == "documento"   # n==1 selects singular form under pt plural rule
    assert i8n.n("document", "documents", 2) == "documentos"


def test_pt_br_telegram_command_messages_resolve_from_catalog(monkeypatch) -> None:
    """
    Every Telegram bot command message id consumed by frontend.telegram.messages should resolve to its pt_BR
    translation from the generated catalog (instead of the English msgid), proving that scripts/gen_locale_catalogs
    keeps the telegram ids in both checked-in locale strings files and that placeholder-free substitution works end-to-end.
    """
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "pt_BR")
    i8n._catalog_for.cache_clear()
    import frontend.telegram.messages as bot_messages

    assert (
        i8n.t(bot_messages.MSG_EMAIL_HINT) == "Por favor, informe o e-mail: /email seu@email.com"
    )
    assert i8n.t(bot_messages.MSG_START_TEXT).startswith("Olá! Envie um PDF")
    assert "Comandos disponíveis:" in i8n.t(bot_messages.MSG_HELP_TEXT)
    assert "Formatos de entrada aceitos:" in i8n.t(bot_messages.MSG_FORMATS_TEXT)


def test_pt_br_email_configured_placeholder_substitutes(monkeypatch) -> None:
    """
    The e-mail-confirmation msgid keeps an {email} placeholder for callers; t() must hand it back untouched so the
    Telegram handler can .format(...) the address in after lookup, with the localized pt_BR wording around it.
    """
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "pt_BR")
    i8n._catalog_for.cache_clear()
    import frontend.telegram.messages as bot_messages

    rendered = i8n.t(bot_messages.MSG_EMAIL_CONFIGURED).format(email="x@y.com")
    assert rendered == ("E-mail x@y.com configurado! Agora envie o documento para ser enviado para este e-mail.")


def test_catalog_validator_flags_missing_translations() -> None:
    """
    Non-default locale translation tables missing any of MESSAGES ids (or with blank values) should be reported by the validator
    as one problem line per unresolved msgid, so build_locales can refuse to write incomplete catalogs.
    """
    empty_table = {loc: {} for loc in gen_locales.SUPPORTED_LOCALES if loc != gen_locales.DEFAULT_LOCALE}
    problems_empty = gen_locales._validate(empty_table, gen_locales.SUPPORTED_LOCALES)
    expected_missing = [f"missing or blank entry: {msgid!r}" for msgid in gen_locales.MESSAGES]
    assert sorted(problems_empty) == sorted(expected_missing)
    partially_blank_table = {
        loc: {gen_locales.MESSAGES[0]: "", } for loc in empty_table

    }
    problems_partial = gen_locales._validate(partially_blank_table, gen_locales.SUPPORTED_LOCALES)
    assert sorted(problems_partial) == sorted(expected_missing)


def test_default_checked_in_catalog_tree_is_generated_by_repo_layout() -> None:
    """Running build_locales against the default backend/locales root should produce complete .po/.mo pairs for both locales."""
    gen_locales.build_locales(DEFAULT_REPOS_CATALOGS_DIR)
    assert (DEFAULT_REPOS_CATALOGS_DIR / "en_US" / "LC_MESSAGES" / "messages.po").is_file()
    assert (DEFAULT_REPOS_CATALOGS_DIR / "en_US" / "LC_MESSAGES" / "messages.mo").is_file()
    assert (DEFAULT_REPOS_CATALOGS_DIR / "pt_BR" / "LC_MESSAGES" / "messages.po").is_file()
    assert (DEFAULT_REPOS_CATALOGS_DIR / "pt_BR" / "LC_MESSAGES" / "messages.mo").is_file()


def test_server_locale_negotiated_from_shell_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """
    The server-side locale should negotiate from the shell environment (no LOCALE set): a Portuguese shell locale
    maps to pt_BR, an English one to en_US, and a C/POSIX locale (no translatable language) falls back to en_US.
    """
    monkeypatch.delenv("LOCALE", raising=False)
    monkeypatch.delenv("LANGUAGE", raising=False)
    monkeypatch.delenv("LC_ALL", raising=False)
    monkeypatch.setenv("LANG", "pt_BR.UTF-8")
    assert i8n._active_locale() == "pt_BR"
    monkeypatch.setenv("LANG", "en_US.UTF-8")
    assert i8n._active_locale() == "en_US"
    monkeypatch.setenv("LANG", "C")
    assert i8n._active_locale() == "en_US"


def test_env_locale_value_overrides_shell_locale(monkeypatch: pytest.MonkeyPatch) -> None:
    """A set LOCALE value (e.g. from .env) takes precedence over the shell environment locale."""
    monkeypatch.setenv("LOCALE", "pt_BR")
    monkeypatch.setenv("LANG", "en_US.UTF-8")
    assert i8n._active_locale() == "pt_BR"


def test_locale_for_user_matches_offered_locale(monkeypatch: pytest.MonkeyPatch) -> None:
    """
    Remote users advertising a Portuguese hint (base 'pt', 'pt-BR' or with an encoding tail) should map to the offered
    pt_BR locale; English hints map to en_US; unmatched or absent hints fall back to the server-side locale.
    """
    monkeypatch.setenv("LOCALE", "en_US")
    assert i8n.locale_for_user("pt") == "pt_BR"
    assert i8n.locale_for_user("pt-BR") == "pt_BR"
    assert i8n.locale_for_user("pt_BR.UTF-8") == "pt_BR"
    assert i8n.locale_for_user("en") == "en_US"
    assert i8n.locale_for_user("en-US") == "en_US"
    assert i8n.locale_for_user("es") == "en_US"
    assert i8n.locale_for_user(None) == "en_US"


def test_set_request_locale_overrides_server_locale(monkeypatch: pytest.MonkeyPatch) -> None:
    """
    Within a task, set_request_locale should redirect t() to the user locale even when the server locale differs, and
    reset_request_locale should restore the server-side locale afterwards.
    """
    _build_and_repoint(monkeypatch)
    monkeypatch.setenv("LOCALE", "en_US")
    i8n._catalog_for.cache_clear()
    assert i8n.t("Downloading file...") == "Downloading file..."
    token = i8n.set_request_locale("pt_BR")
    i8n._catalog_for.cache_clear()
    assert i8n.t("Downloading file...") == "Baixando arquivo..."
    i8n.reset_request_locale(token)
    i8n._catalog_for.cache_clear()
    assert i8n.t("Downloading file...") == "Downloading file..."
